### ISSUE TITLE
Convert to namespace plugin

### ISSUE THREAD

**Issue by justinmayer** [pelican-plugins/graphviz#1]
This issue tracks conversion to a namespace plugin and eventual packaging and distribution to PyPI:

* [x] Create new repository and import commits from [previous repository](https://github.com/rlaboiss/pelican_md_graphviz)
* [x] Add CI/CD environment variables needed for AutoPub-powered automatic releases
* [x] Convert to namespace plugin
* [x] Fix tests, if needed
* [x] Fix functional issues with migrated plugin, if any
* [x] Apply code style conventions to new repo
* [x] Update new repo README
* [x] Setup CI/CD by the way of GitHub workflows
* [x] Release v1.0.0 on PyPI

**Comment by rlaboiss** [comment]
@justinmayer: Thanks a lot for this initial work regarding the migration of the graphviz plugin, it is really appreciated. I am also excited to see this plugin migrated.

I will be very busy during the next week and, since there are many things to be learned on my side, I will not be able to do any actual work on this until the weekend of March 6.

**Comment by rlaboiss** [comment]
I created the pull request (#2).

Notice that I mistakenly pushed the very first commit of the migration (0255904) into the `main` branch and not into the `migrate` branch, as it should have been done. I apologize for this mistake.

**Comment by rlaboiss** [comment]
I pushed some more commits to the migrate branch, to avoid linters warnings (4767005), to fix a problem with the GitHub workflow (70e0b5c) and to add another unit test (53217d1).
